In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import load_digits
digits = load_digits()

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size =0.3)

In [4]:
from sklearn.linear_model import LogisticRegression

In [5]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9611111111111111

In [6]:
from sklearn.svm import SVC

In [7]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.987037037037037

In [8]:
from sklearn.ensemble import RandomForestClassifier

In [9]:
rm = RandomForestClassifier(n_estimators=40)
rm.fit(X_train,y_train)
rm.score(X_test,y_test)

0.9685185185185186

In [10]:
from sklearn.model_selection import KFold
# from sklearn.model_selection import KFold
kf= KFold(n_splits=3 )
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [11]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9,5,3,2,1,3]):
    print(train_index,test_index)

[ 5  6  7  8  9 10 11 12 13] [0 1 2 3 4]
[ 0  1  2  3  4 10 11 12 13] [5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9] [10 11 12 13]


In [12]:
def get_score(model, X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [13]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.987037037037037

In [14]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [15]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index], \
                                    digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

In [16]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [17]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [18]:
scores_rf

[0.9298831385642737, 0.9532554257095158, 0.9232053422370617]

In [19]:
from sklearn.model_selection import cross_val_score

In [20]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [21]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [22]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.93333333, 0.90833333, 0.94986072, 0.96100279, 0.91086351])

In [23]:
cross_val_score(RandomForestClassifier(n_estimators=15),digits.data,digits.target)

array([0.90555556, 0.86944444, 0.95264624, 0.94986072, 0.90529248])

In [24]:
cross_val_score(RandomForestClassifier(n_estimators=555),digits.data,digits.target)

array([0.93055556, 0.91666667, 0.95543175, 0.96657382, 0.93314763])